### ISSUE TITLE
hk2-bom:2.6.0 is not usable

### ISSUE THREAD

**Issue by romain-grecourt** [eclipse-ee4j/glassfish-hk2#470]
One gets the following error when import hk2-bom:2.6.0.

```
[WARNING] The POM for org.ow2.asm:asm:jar:${asm.version} is missing, no dependency information available
[WARNING] The POM for org.ow2.asm:asm-analysis:jar:${asm.version} is missing, no dependency information available
[WARNING] The POM for org.ow2.asm:asm-commons:jar:${asm.version} is missing, no dependency information available
[WARNING] The POM for org.ow2.asm:asm-tree:jar:${asm.version} is missing, no dependency information available
[WARNING] The POM for org.ow2.asm:asm-util:jar:${asm.version} is missing, no dependency information available
```

The issue is that it references `${asm.version}` which is defined only in the parent pom, however the bom does not inherit the parent pom.

**Comment by smillidge** [comment]
Fixed by #471

**Comment by xvik** [comment]
After reverting proposed fix (parent pom reverted to generic eclipse ee parent), `asm.version` property was not added and so current BOM is still not valid (2.6.1 release is affected).
